apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: aksautoapp
  labels:
    app.kubernetes.io/name: aksautoapp
    app.kubernetes.io/part-of: aksautoapp-project
    kubernetes.azure.com/generator: devhub
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: aksautoapp